#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
	local enabled="$(uci -q get mqttsub.@mqttsub[0].enabled)"
	if [ "$enabled" -ne 1 ]; then
		return
	fi

	procd_open_instance
	procd_set_param command /usr/sbin/mqttsub
	procd_set_param file /etc/config/mqttsub
	procd_set_param term_timeout 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "mqttsub"
}

reload_service() {
	stop
	start
}
